"""create_tables

Revision ID: e0f3695c9c90
Revises:
Create Date: 2024-08-04 18:44:50.951645

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0f3695c9c90"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "texts",
        sa.Column("id_", sa.BigInteger(), nullable=False),
        sa.Column("not_sub_text", sa.String(), nullable=False),
        sa.Column("manual_text", sa.String(), nullable=False),
        sa.Column("main_text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("texts")
    # ### end Alembic commands ###
